# Generated by Django 6.1 on 2026-08-17 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre de la séance')),
                ('niveau', models.CharField(choices=[('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('AUTRE', 'Autre niveau')], default='CM1', max_length=10)),
                ('matiere', models.CharField(choices=[('FR', 'Français'), ('MATHS', 'Mathématiques'), ('HIST_GEO', 'Histoire - Géographie'), ('SCIENCES', 'Sciences et Technologie'), ('EPS', 'Éducation Physique et Sportive'), ('ARTS', 'Arts Plastiques / Musique'), ('ANGLAIS', 'Langue vivante'), ('AUTRE', 'Autre matière')], default='MATHS', max_length=20)),
                ('theme', models.CharField(help_text='Ex: Les fractions, Le passé composé...', max_length=255)),
                ('duree_minutes', models.PositiveIntegerField(default=45, verbose_name='Durée (min)')),
                ('objectifs', models.TextField(blank=True, verbose_name='Objectifs pédagogiques')),
                ('deroule_seance', models.TextField(blank=True, verbose_name='Déroulé de la séance (5 phases)')),
                ('exercices_types', models.TextField(blank=True, verbose_name="Exercices d'application")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_preparation', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Fiche de préparation',
                'verbose_name_plural': 'Fiches de préparation',
                'ordering': ['-date_creation'],
            },
        ),
    ]
