# Generated by Django 6.1 on 2026-08-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepreparation',
            name='matiere',
            field=models.CharField(choices=[('FR', 'Français / Lettres'), ('MATHS', 'Mathématiques'), ('HIST_GEO', 'Histoire - Géographie - EMC'), ('SCIENCES', 'Sciences et Technologie'), ('SVT', 'Sciences de la Vie et de la Terre (SVT)'), ('PC', 'Physique - Chimie'), ('EPS', 'Éducation Physique et Sportive'), ('ARTS', 'Arts Plastiques / Éducation Musicale'), ('LV', 'Langues vivantes'), ('PHILO', 'Philosophie'), ('SES', 'Sciences Économiques et Sociales'), ('NSI_TECH', 'Technologie / Numérique et Informatique (NSI)'), ('AUTRE', 'Autre discipline')], default='MATHS', max_length=20),
        ),
        migrations.AlterField(
            model_name='fichepreparation',
            name='niveau',
            field=models.CharField(choices=[('PS', 'Petite Section'), ('MS', 'Moyenne Section'), ('GS', 'Grande Section'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6E', '6ème'), ('5E', '5ème'), ('4E', '4ème'), ('3E', '3ème'), ('2NDE', 'Seconde'), ('1ERE', 'Première'), ('TERM', 'Terminale'), ('AUTRE', 'Autre niveau')], default='CM1', max_length=10),
        ),
        migrations.AlterField(
            model_name='fichepreparation',
            name='theme',
            field=models.CharField(help_text='Ex: Les fractions simples, Le passé composé...', max_length=255),
        ),
    ]
