# Generated by Django 6.1 on 2026-08-18 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparations', '0002_alter_fichepreparation_matiere_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationQCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du QCM')),
                ('niveau', models.CharField(choices=[('PS', 'Petite Section'), ('MS', 'Moyenne Section'), ('GS', 'Grande Section'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6E', '6ème'), ('5E', '5ème'), ('4E', '4ème'), ('3E', '3ème'), ('2NDE', 'Seconde'), ('1ERE', 'Première'), ('TERM', 'Terminale'), ('AUTRE', 'Autre niveau')], default='CM1', max_length=10)),
                ('matiere', models.CharField(choices=[('FR', 'Français / Lettres'), ('MATHS', 'Mathématiques'), ('HIST_GEO', 'Histoire - Géographie - EMC'), ('SCIENCES', 'Sciences et Technologie'), ('SVT', 'Sciences de la Vie et de la Terre (SVT)'), ('PC', 'Physique - Chimie'), ('EPS', 'Éducation Physique et Sportive'), ('ARTS', 'Arts Plastiques / Éducation Musicale'), ('LV', 'Langues vivantes'), ('PHILO', 'Philosophie'), ('SES', 'Sciences Économiques et Sociales'), ('NSI_TECH', 'Technologie / Numérique et Informatique (NSI)'), ('AUTRE', 'Autre discipline')], default='MATHS', max_length=20)),
                ('notions_cles', models.CharField(help_text='Ex: Accords participe passé, fractions équivalentes...', max_length=255)),
                ('difficulte', models.CharField(choices=[('FACILE', 'Facile / Découverte'), ('MOYEN', 'Intermédiaire / Standard'), ('AVANCE', 'Avancé / Approfondissement')], default='MOYEN', max_length=10)),
                ('nb_questions', models.PositiveIntegerField(default=5, verbose_name='Nombre de questions')),
                ('contenu_eleve', models.TextField(blank=True, verbose_name='Sujet Élève (QCM)')),
                ('contenu_corrige', models.TextField(blank=True, verbose_name='Corrigé Enseignant')),
                ('pistes_remediation', models.TextField(blank=True, verbose_name='Pistes de remédiation & Différenciation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_qcm', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Évaluation QCM',
                'verbose_name_plural': 'Évaluations QCM',
                'ordering': ['-date_creation'],
            },
        ),
    ]
